### ISSUE TITLE
Transform errors in rviz, missing arms

### ISSUE THREAD

**Issue by fweiss1** [Arn-O/youbot_ros_tools#4]
Hello,
I used your package but there were the following problems
using roslaunch youbot_description youbot_publisher.launch:
Arms 2 - 5 are not displayed. The rest of the robot has transform base errors like in this picture:
![transform_error](https://cloud.githubusercontent.com/assets/10423305/5632695/fa1ab886-95d0-11e4-8344-676367008a53.png)

Arms 2 - 5 are uncommented in the youbot.urdf.xacro. If I undo this commenting, these arms are not displayed in rviz but the joint_state_publisher for all the arms opens, before this just for arm_1.

So how can I display the whole Youbot with all its arms without the base_transform errors?

**Comment by Arn-O** [comment]
Hi.

Did you comment everything, links and joints? I do not have a running ROS system, not easy to help.

**Comment by fweiss1** [comment]
I did UNcomment everything, links and joints

    
    <link name="arm_2_link">
      <inertial>
        <xacro:arm_2_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_2.dae"/>
        </geometry>
      </visual>
    </link>
    
    <joint name="arm_2_joint" type="revolute">
      <xacro:arm_2_joint/>
      <child link="arm_2_link"/>
    </joint>
    <transmission name="tran2">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_2_joint"/>
      <actuator name="motor2">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
Same for the other arms

**Comment by fweiss1** [comment]
Can you guess, where all these transform base errors come from?

**Comment by Arn-O** [comment]
Is it working for another robot description, like the rrbot?

**Comment by fweiss1** [comment]
Idon't know. This is my first try with this kind of stuff. 
Any suggestions for a description I could try?

**Comment by Arn-O** [comment]
You should try the following robot: https://github.com/ros-simulation/gazebo_ros_demos

That will validate that your ROS install is fine.

**Comment by fweiss1** [comment]
That is absolutely crazy. I restarted my computer and now everything is ok.
I do not know, why this happens and if it happens again I need luck so that it disappears again^^
That's kind of nondeterministic^^

**Comment by Arn-O** [comment]
OK, so let's close this issue. By experience, ROS is quite "sensitive". I had unexplained bugs several times. Have fun with the youBot! By the way, to not hesitate to improve this repository.
